/* Generated by the OncOS kit (oncos_sw.py) — do not hand-edit.
 * Cache name is a content hash of the app files, so each real change ships a
 * fresh cache. Fetch is NETWORK-FIRST: try the network, fall back to cache
 * offline. This is the OncOS PWA rule — never date-versioned cache-first. */
const CACHE = 'oncos-one-8750ce1e8732';
const CACHE_PREFIX = 'oncos-one-';
const ASSETS = [
  '././',
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  './apple-touch-icon-180.png',
  './views/evidence.html',
  './views/staging.html',
  './views/drugs.html',
  './views/tox.html',
  './views/acute.html',
  './fonts/Montserrat-normal-700.woff2',
  './fonts/Newsreader-normal-200_800.woff2',
  './fonts/SchibstedGrotesk-normal-400_900.woff2',
  './fonts/SchibstedGrotesk-italic-400_900.woff2',
  './fonts/SplineSansMono-normal-300_700.woff2'
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE)
        .map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;
  // Vercel internals (analytics script + beacons) are never ours to cache or to
  // serve an offline fallback for. Only the hub's SW is root-scoped enough to
  // see these; module SWs are scoped to their own subpath.
  if (new URL(e.request.url).pathname.startsWith('/_vercel/')) return;
  e.respondWith(
    fetch(e.request)
      .then((resp) => {
        // Never replace a valid offline asset with a password-gate response,
        // server error, redirect, or other non-success response.
        if (resp.ok && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
        }
        return resp;
      })
      .catch(() => caches.match(e.request).then((hit) => {
        if (hit) return hit;
        if (e.request.mode === 'navigate') return caches.match('./index.html');
        return Response.error();
      }))
  );
});
